export const SAVE_MESSAGE = 'saveMessage'
export const GET_MESSAGES = 'getMessages'
export const CREATE_USER = 'createUser'
export const VERIFY_USER = 'verifyUser'
export const CREATE_GROUP = 'createGroup'
